### ISSUE TITLE
Script still running when stopped

### ISSUE THREAD

**Issue by kalikot26** [dante4rt/getgrass-bot#12]
I noticed that they uploaded a new version and this version will keep running even you stopped the script (ctrl+c) been 5hrs now since I stopped and deleted all the getgrass-bot files my dashboard stills says that there are devices connected and I’m earning 0

**Comment by 9840144** [comment]
me too

**Comment by 0xAlvi** [comment]
this is because the web grass still has a lot of bugs, don't worry too much about it and if every morning your points are dropped it's a bug again, we all experience it and points will be normal late in the day

**Comment by dante4rt** [comment]
> I noticed that they uploaded a new version and this version will keep running even you stopped the script (ctrl+c) been 5hrs now since I stopped and deleted all the getgrass-bot files my dashboard stills says that there are devices connected and I’m earning 0

Bug (glitch) on Grass dashboard.

**Comment by ceifeDeFi** [comment]
> I noticed that they uploaded a new version and this version will keep running even you stopped the script (ctrl+c) been 5hrs now since I stopped and deleted all the getgrass-bot files my dashboard stills says that there are devices connected and I’m earning 0

This my problem too
