### ISSUE TITLE
Cara Menggunakan Getgrass-Bot untuk Farming Airdrop Grass kontenterabox.com

### ISSUE THREAD

**Issue by ayumustika2025** [dante4rt/getgrass-bot#15]
**Cara Menggunakan Getgrass-Bot untuk Farming Airdrop Grass**

Jika kamu tertarik buat farming airdrop Grass, kamu bisa coba pakai `getgrass-bot`. Bot ini dibuat untuk menghubungkan WebSocket lewat HTTP dan SOCKS proxies, cocok banget buat yang pengen lebih fleksibel dan bisa menggunakan berbagai tipe proxy. Gampang banget cara pakainya, pertama clone dulu repository-nya, install dependensi dengan npm, lalu siapin file `uid.txt` dan `proxy.txt` buat ID dan proxy kamu. Setelah itu tinggal jalankan botnya pakai perintah `npm start`. 

Kalau lagi cari solusi buat storage dan akses data yang cepat dan aman, coba deh cek **[konten terabox](https://kontenterabox.com)**.

**Comment by dante4rt** [comment]
> **Cara Menggunakan Getgrass-Bot untuk Farming Airdrop Grass**
> 
> Jika kamu tertarik buat farming airdrop Grass, kamu bisa coba pakai `getgrass-bot`. Bot ini dibuat untuk menghubungkan WebSocket lewat HTTP dan SOCKS proxies, cocok banget buat yang pengen lebih fleksibel dan bisa menggunakan berbagai tipe proxy. Gampang banget cara pakainya, pertama clone dulu repository-nya, install dependensi dengan npm, lalu siapin file `uid.txt` dan `proxy.txt` buat ID dan proxy kamu. Setelah itu tinggal jalankan botnya pakai perintah `npm start`.
> 
> Kalau lagi cari solusi buat storage dan akses data yang cepat dan aman, coba deh cek **[konten terabox](https://kontenterabox.com)**.

smh.
