### ISSUE TITLE
Fix for econnrefused on working socks proxy and added few servers

### ISSUE THREAD

**Issue by lester51** [dante4rt/getgrass-bot#19]
I did a little change here in `./src/Bot.js` to fix the error malformed socks proxy `econnrefused` on working socks proxy links like this `socks5://socks4://{PROXY}:{PORT}` and adjusted to somehow if the returned proxy doesnt have protocol or proxy (http/socks) in your proxy formater line.

![Screenshot_2024_1108_182226](https://github.com/user-attachments/assets/4c33694c-49c1-490b-9494-b32862d41eaa)

I also did add a few more free servers available on github that is automatically updated everyday.

![Screenshot_2024_1108_173949](https://github.com/user-attachments/assets/45217fab-7a44-4669-9b4d-b5f33739416d)

IMPORTANT ISSUE NEEDED TO BE FIXED IS ON YOUR PROXY FORMATTER.

**Comment by dante4rt** [comment]
> I did a little change here in `./src/Bot.js` to fix the error malformed socks proxy `econnrefused` on working socks proxy links like this `socks5://socks4://{PROXY}:{PORT}` and adjusted to somehow if the returned proxy doesnt have protocol or proxy (http/socks) in your proxy formater line.
> 
> ![Screenshot_2024_1108_182226](https://private-user-images.githubusercontent.com/68170831/384328608-4c33694c-49c1-490b-9494-b32862d41eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDEwNDIsIm5iZiI6MTczMTc0MDc0MiwicGF0aCI6Ii82ODE3MDgzMS8zODQzMjg2MDgtNGMzMzY5NGMtNDljMS00OTBiLTk0OTQtYjMyODYyZDQxZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA3MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNGVmYmE2MGVlMTRmNWY4MDYzMDRhNzY3YzFjYmJiZjk5MGY1MmNjNDQ3ZjdhMDEyMGM5ZTI0ZGM3Nzg2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w70x6lxr5ac077ot2oq8N7K7i1fYMnhbrHX2dqIbujg)
> 
> I also did add a few more free servers available on github that is automatically updated everyday.
> 
> ![Screenshot_2024_1108_173949](https://private-user-images.githubusercontent.com/68170831/384317313-45217fab-7a44-4669-9b4d-b5f33739416d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDEwNDIsIm5iZiI6MTczMTc0MDc0MiwicGF0aCI6Ii82ODE3MDgzMS8zODQzMTczMTMtNDUyMTdmYWItN2E0NC00NjY5LTliNGQtYjVmMzM3Mzk0MTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA3MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDNiN2FkOWRlOGNkYjVjNTE5MmVhZDJhODU1ODQxNWMxNmUzMTMwMTE3ZTI4MzI4MGVhNTBiYjE4Yjc3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.znKTYfNUu2i51nMBqT2NelkJHMrFoRJd5oS9-IU0-1c)
> 
> IMPORTANT ISSUE NEEDED TO BE FIXED IS ON YOUR PROXY FORMATTER.

Please open a PR and I will merge it, thanks.
