### ISSUE TITLE
请问支持socks5代理吗？

### ISSUE THREAD

**Issue by largeHe1982** [dante4rt/getgrass-bot#2]
请问支持socks5代理吗？

**Comment by dante4rt** [comment]
> 请问支持socks5代理吗？

I have not tried it yet, as I always attempt to use HTTP or HTTPS.

**Comment by darknessus** [comment]
not working with smart proxy http or https

**Comment by yayaQAQ** [comment]
I you want to use socks5,  you can use another repo, https://github.com/ymmmmmmmm/getgrass_bot
