### ISSUE TITLE
ws error 1006

### ISSUE THREAD

**Issue by yopiucing** [dante4rt/getgrass-bot#22]
![IMG_20241111_123557](https://github.com/user-attachments/assets/ccbb9979-936b-4637-a5e4-4c72f8f83634)

**Comment by 0xAlvi** [comment]
check your proxy

**Comment by dante4rt** [comment]
> ![IMG_20241111_123557](https://private-user-images.githubusercontent.com/116066417/384793293-ccbb9979-936b-4637-a5e4-4c72f8f83634.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDEwMDAsIm5iZiI6MTczMTc0MDcwMCwicGF0aCI6Ii8xMTYwNjY0MTcvMzg0NzkzMjkzLWNjYmI5OTc5LTkzNmItNDYzNy1hNWU0LTRjNzJmOGY4MzYzNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwNzA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWExNDNhZGQwOGFmYmI2N2RkOTVkNTI1ZTQ3Y2Q3ZGM3Y2M3Y2Y0ODRhMjI1NDhiZjJmN2I1NmM5OTRkMzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VvGyiUXAYNxCaTYAwPBPsrnSn6FRl7O9LYR2TZ4pzHs)

Proxy problem.
