### ISSUE TITLE
Proxy score integration and checker

### ISSUE THREAD

**Issue by Mattias16-beep** [dante4rt/getgrass-bot#26]
Hello, this script seems to be working well since I tested it for 6 hours.

It could be a great idea to add a proxy score checker, and remove any proxy from the list if it has a low score.

I sent 4 proxies on my list, and only 2 are working properly, while the others keep sending pings even though they’re disconnected from Getgrass.

**Comment by dante4rt** [comment]
> Hello, this script seems to be working well since I tested it for 6 hours.
> 
> It could be a great idea to add a proxy score checker, and remove any proxy from the list if it has a low score.
> 
> I sent 4 proxies on my list, and only 2 are working properly, while the others keep sending pings even though they’re disconnected from Getgrass.

Great idea, thanks. Will figured out how to implement it.
