### ISSUE TITLE
Multiple account IP issues

### ISSUE THREAD

**Issue by zhanghengg** [dante4rt/getgrass-bot#27]
Currently, one account corresponds to multiple agents, and vice versa. Isn't this a witch? I temporarily changed it to 1v1, thks
In addition, i used my own ip proxy

**Comment by dante4rt** [comment]
> Currently, one account corresponds to multiple agents, and vice versa. Isn't this a witch? I temporarily changed it to 1v1, thks In addition, i used my own ip proxy

It's common, Grass allow us to use multiple devices to connect on 1 account. But, if your proxy is SHARED, then it will be detected as Sybil.
