### ISSUE TITLE
In the CUSTOM mode, how to edit the format of socks5 in the proxy.txt file?

### ISSUE THREAD

**Issue by 641813435** [dante4rt/getgrass-bot#32]
The following is not in the right format.

![image](https://github.com/user-attachments/assets/e1274931-24ba-4bfe-9a50-893f3d8a9482)

**Comment by dante4rt** [comment]
> The following is not in the right format.
> 
> ![image](https://private-user-images.githubusercontent.com/40487877/386938523-e1274931-24ba-4bfe-9a50-893f3d8a9482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mzc3MzUsIm5iZiI6MTczMTgzNzQzNSwicGF0aCI6Ii80MDQ4Nzg3Ny8zODY5Mzg1MjMtZTEyNzQ5MzEtMjRiYS00YmZlLTlhNTAtODkzZjNkOGE5NDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA5NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMzI4NGUxMmNjOWY4OGVlZGM2YTRhNjljMDhiZDM4ODA1NTg3MjlmZjZkYTgzNDA3MGQ0ZDJjZDdmMTZkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KMSkFkcgwlA1fMqI_tUnsKUsgWXvsW5gAjgclSIF5gw)

Fixed here:
https://github.com/dante4rt/getgrass-bot/commit/34472ca97bfa3803b7d25532edaea3d5bbce3ce9

Thanks.
