### ISSUE TITLE
What kind of IP

### ISSUE THREAD

**Issue by vayne666** [dante4rt/getgrass-bot#36]
Hey  What kind of ip should I buy Residential or  Static Residential

**Comment by zamiguinbra** [comment]
residential proxy, at the end of the page you can choose the $2 plan for this function, I'm using it and it's working
https://proxyscrape.com/products/residential-proxies/

**Comment by vayne666** [comment]
> 住宅代理，在页面末尾，您可以选择此功能的 2 美元计划，我正在使用它并且它正在工作 https://proxyscrape.com/products/residential-proxies/

okay thank you
