### ISSUE TITLE
is this working?

### ISSUE THREAD

**Issue by nmluthfi** [dante4rt/getgrass-bot#4]
{"id":"0c117a1e-05c2-4c63-9ad1-eadaecbf3192","version":"1.0.0","action":"PING","data":{}}
{ id: 'nTa', action: 'PONG' }
{ id: 'nTa', origin_action: 'PONG' }
WebSocket connection opened
{"id":"99cd41a6-7dfc-401b-ae6a-4c4b7f1a3aee","version":"1.0.0","action":"PING","data":{}}
{"id":"4007fffc-ab2c-4ddf-a3e1-f1c47b829282","version":"1.0.0","action":"PING","data":{}}
{"id":"f9aad718-d7a2-4540-a7ab-1db8d5a79087","version":"1.0.0","action":"PING","data":{}}
WebSocket connection closed
{ id: '8dm', action: 'PONG' }
{ id: '8dm', origin_action: 'PONG' }
{"id":"aa06a2d4-45ed-4984-8a34-fbd08cc408f6","version":"1.0.0","action":"PING","data":{}}
{ id: '9km', action: 'PONG' }
{ id: '9km', origin_action: 'PONG' }
{"id":"8477bb20-4b5d-4831-9913-082d616bbc6a","version":"1.0.0","action":"PING","data":{}}
{"id":"529ae652-317d-42dc-8cca-36d4ba88f98b","version":"1.0.0","action":"PING","data":{}}
WebSocket connection closed
{"id":"eef45948-0342-4e6d-92b1-37454f69d90c","version":"1.0.0","action":"PING","data":{}}
{"id":"f7e7958e-5bc7-4d2e-8573-078d61aa9fdc","version":"1.0.0","action":"PING","data":{}}
{ id: '1Th', action: 'PONG' }
{ id: '1Th', origin_action: 'PONG' }
{"id":"391eed6f-aa44-465c-a53e-545235deb9b3","version":"1.0.0","action":"PING","data":{}}
{"id":"9df6c7c5-2fba-4b70-bfe8-caab48c87772","version":"1.0.0","action":"PING","data":{}}
{"id":"5893d356-324e-4511-91c6-b4352f4c687c","version":"1.0.0","action":"PING","data":{}}
WebSocket connection opened
{"id":"bd9c2523-becf-435e-b20b-1c0d4f6ebb0b","version":"1.0.0","action":"PING","data":{}}
WebSocket connection closed
WebSocket connection closed
{"id":"1fb9d472-5867-4b12-9821-bf3f14f21eb5","version":"1.0.0","action":"PING","data":{}}
WebSocket connection opened
{ id: 'rgN', action: 'PONG' }
{ id: 'rgN', origin_action: 'PONG' }
{"id":"52b59839-34cc-4b11-b0f9-4e856df76fdc","version":"1.0.0","action":"PING","data":{}}
{"id":"777c229c-54d4-4886-8897-247c0a297385","version":"1.0.0","action":"PING","data":{}}
{"id":"659e915c-ce5a-4180-a714-0fc860e41324","version":"1.0.0","action":"PING","data":{}}

**Comment by dante4rt** [comment]
> {"id":"0c117a1e-05c2-4c63-9ad1-eadaecbf3192","version":"1.0.0","action":"PING","data":{}} { id: 'nTa', action: 'PONG' } { id: 'nTa', origin_action: 'PONG' } WebSocket connection opened {"id":"99cd41a6-7dfc-401b-ae6a-4c4b7f1a3aee","version":"1.0.0","action":"PING","data":{}} {"id":"4007fffc-ab2c-4ddf-a3e1-f1c47b829282","version":"1.0.0","action":"PING","data":{}} {"id":"f9aad718-d7a2-4540-a7ab-1db8d5a79087","version":"1.0.0","action":"PING","data":{}} WebSocket connection closed { id: '8dm', action: 'PONG' } { id: '8dm', origin_action: 'PONG' } {"id":"aa06a2d4-45ed-4984-8a34-fbd08cc408f6","version":"1.0.0","action":"PING","data":{}} { id: '9km', action: 'PONG' } { id: '9km', origin_action: 'PONG' } {"id":"8477bb20-4b5d-4831-9913-082d616bbc6a","version":"1.0.0","action":"PING","data":{}} {"id":"529ae652-317d-42dc-8cca-36d4ba88f98b","version":"1.0.0","action":"PING","data":{}} WebSocket connection closed {"id":"eef45948-0342-4e6d-92b1-37454f69d90c","version":"1.0.0","action":"PING","data":{}} {"id":"f7e7958e-5bc7-4d2e-8573-078d61aa9fdc","version":"1.0.0","action":"PING","data":{}} { id: '1Th', action: 'PONG' } { id: '1Th', origin_action: 'PONG' } {"id":"391eed6f-aa44-465c-a53e-545235deb9b3","version":"1.0.0","action":"PING","data":{}} {"id":"9df6c7c5-2fba-4b70-bfe8-caab48c87772","version":"1.0.0","action":"PING","data":{}} {"id":"5893d356-324e-4511-91c6-b4352f4c687c","version":"1.0.0","action":"PING","data":{}} WebSocket connection opened {"id":"bd9c2523-becf-435e-b20b-1c0d4f6ebb0b","version":"1.0.0","action":"PING","data":{}} WebSocket connection closed WebSocket connection closed {"id":"1fb9d472-5867-4b12-9821-bf3f14f21eb5","version":"1.0.0","action":"PING","data":{}} WebSocket connection opened { id: 'rgN', action: 'PONG' } { id: 'rgN', origin_action: 'PONG' } {"id":"52b59839-34cc-4b11-b0f9-4e856df76fdc","version":"1.0.0","action":"PING","data":{}} {"id":"777c229c-54d4-4886-8897-247c0a297385","version":"1.0.0","action":"PING","data":{}} {"id":"659e915c-ce5a-4180-a714-0fc860e41324","version":"1.0.0","action":"PING","data":{}}

Check new version, it works.
